### ISSUE TITLE
Website in Different Screen sizes

### ISSUE THREAD

**Issue by harmansohanpal** [nitishMehrotra/PnPWebsite#2]
Website bug to be sorted.Despite website being adaptive to screen size segments in the website are not a part of different screen segments. Please check and revert

**Comment by aggarwalakhil9** [comment]
this is due to background image. We'll have a proper background image with appropriate dimensions for different screen resolution.

**Comment by nitishMehrotra** [comment]
The bottom margin that is coming on some of the devices will contiue to come. This is because of different screen resolutions.
