### ISSUE TITLE
Icons not coming

### ISSUE THREAD

**Issue by nitishMehrotra** [nitishMehrotra/PnPWebsite#9]
Facebook/Twitter/LinkedIn/Github icons are not coming

**Comment by aggarwalakhil9** [comment]
the issue is only sometimes. Needs investigation

**Comment by aggarwalakhil9** [comment]
resolved. used below link to resolve (for reference)
https://wordpress.org/support/topic/social-media-icons-not-working-on-zerif-lite

changed .htaccess file in word press installation directory
